### ISSUE TITLE
Get donation link from package.json

### ISSUE THREAD

**Issue by mappum** [feross/thanks#35] opened 2018-02-10 00:28 UTC
Awesome project (and nice re-use of the name `thanks`)!

Now that it's getting so popular, it might be hard to scale the set of donation links since you would have to keep merging PRs every day. Instead, maybe it makes sense to also check packages for a `donation` field in their package.json, which would just contain the URL.

I'm not sure how you would do author links this way though.

**Comment by adrianheine** [comment] 2018-02-10 00:39
Dupe of #2.

**Comment by feross** [comment] 2018-02-10 00:57
@mappum Yep, you're right. This is already becoming an issue! Let's continue discussion in #2!

**Closed by feross** 2018-02-10 00:57 UTC
